package ca.thecorgi.barrenisles.feature.tree;

import ca.thecorgi.barrenisles.BarrenIsles;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3i;
import net.minecraft.util.math.intprovider.IntProvider;
import net.minecraft.world.TestableWorld;
import net.minecraft.world.gen.feature.TreeFeatureConfig;
import net.minecraft.world.gen.foliage.FoliagePlacer;
import net.minecraft.world.gen.foliage.FoliagePlacerType;

import java.util.Random;
import java.util.function.BiConsumer;

public class PalmFoliagePlacer extends FoliagePlacer {
    // For the foliageHeight we use a codec generated by IntProvider.createValidatingCodec
    // As the method's arguments, we pass in the minimum and maximum value of the IntProvider
    // To add more fields into your TrunkPlacer/FoliagePlacer/TreeDecorator etc., use multiple .and calls
    //
    // For an example of creating your own type of codec, see the IntProvider.createValidatingCodec method's source
    public static final Codec<PalmFoliagePlacer> CODEC = RecordCodecBuilder.create(instance ->
            fillFoliagePlacerFields(instance)
                    .and(IntProvider.createValidatingCodec(1, 512).fieldOf("foliage_height").forGetter(PalmFoliagePlacer::getFoliageHeight)).apply(instance, PalmFoliagePlacer::new));

    private final IntProvider foliageHeight;

    public PalmFoliagePlacer(IntProvider radius, IntProvider offset, IntProvider foliageHeight) {
        super(radius, offset);

        this.foliageHeight = foliageHeight;
    }

    public IntProvider getFoliageHeight() {
        return this.foliageHeight;
    }

    @Override
    protected FoliagePlacerType<?> getType() {
        return BarrenIsles.PALM_FOLIAGE_PLACER;
    }

    @Override
    protected void generate(TestableWorld world, BiConsumer<BlockPos, BlockState> replacer, Random random, TreeFeatureConfig config, int trunkHeight, TreeNode treeNode, int foliageHeight, int radius, int offset) {
        BlockPos.Mutable center = treeNode.getCenter().mutableCopy();

//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 0))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, 0, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, 1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, -1, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, 2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, 0, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, 1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, -1, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, -2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, 2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, 2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, -1, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, -2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, -1, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, 2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -2, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -2, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, 2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 0))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, 0, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, 1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, -1, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, 2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, 0, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, 1, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, -1, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, -2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, 2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, 2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, -1, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, -2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, -1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, -1, 1))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, 2))));
//
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -2, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -2, 0))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, -2))));
//        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, 2))));


        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 0))));

        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, 0, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, -1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, -2, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(1, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(2, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(3, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(3, 0, 0))));

        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, 0, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, -1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, -2, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-1, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-2, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-3, 1, 0))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(-3, 0, 0))));

        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, 1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, 2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, 2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, 1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, 2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, 3))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, 3))));

        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, -1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, -1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -1, -2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, -2, -2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, -1))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, -2))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 1, -3))));
        this.placeFoliageBlock(world, replacer, random, config, new BlockPos(center.add(new Vec3i(0, 0, -3))));


    }

    @Override
    public int getRandomHeight(Random random, int trunkHeight, TreeFeatureConfig config) {
        return foliageHeight.get(random);
    }

    @Override
    protected boolean isInvalidForLeaves(Random random, int dx, int y, int dz, int radius, boolean giantTrunk) {
        // Our FoliagePlacer doesn't set any restrictions on leaves
        return false;
    }
}