modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
	modId="barrenisles"
	version="${file.jarVersion}"
	displayName="Barren Isles"
	authors="The Corgi, Xyndra, Violet, Avila and Trimsky(optional)"
	logoFile="icon.png"
	description=''' The Barren Isles exists to make it a desert a place 
		where a flower could be beautiful and in the next second attempting unsolicited murder.
	'''

[[dependencies.barrenisles]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.barrenisles]]
    modId="minecraft"
    mandatory=true
	versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"	